all: func4.o column_del_1.o 2darr3.o
	gcc func4.o column_del_1.o 2darr3.o && del *.o

func4.o: func4.c
	gcc -c func4.c

column_del_1.o: column_del_1.c
	gcc -c column_del_1.c

2darr3.o: 2darr3.c
	gcc -c 2darr3.c
