all: 2d_arrays_1.o column_del.o delete_max_columns.o
	gcc 2d_arrays_1.o column_del.o delete_max_columns.o && del *.o

2d_arrays_1.o: 2d_arrays_1.c
	gcc -c 2d_arrays_1.c

column_del.o: column_del.c
	gcc -c column_del.c

delete_max_columns.o: delete_max_columns.c
	gcc -c delete_max_columns.c
