all: func2.o column_del.o 2d_arrays_2.o
	gcc func2.o column_del.o 2d_arrays_2.o && del *.o

func2.o: func2.c
	gcc -c func2.c

column_del.o: column_del.c
	gcc -c column_del.c

2d_arrays_2.o: 2d_arrays_2.c
	gcc -c 2d_arrays_2.c
